version: "3.8"

services:
  app:
    command: sleep infinity
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args: 
        NODE_VERSION: "none"
    volumes:
      - ..:/docker-cookiecutter
    environment: 
      DEV_CONTAINER: "1"
